os:
  - osx
install:
  - brew update
  - brew install gauge
  - brew outdated maven || brew upgrade maven
  - mvn -version
language: csharp
jdk:
  - oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - ./build.sh BuildInstallFT