os:
  - osx
before_install:
  - brew update; brew install Caskroom/cask/java
install:
  - brew install gauge; brew outdated maven || brew upgrade maven
  - mvn -version
language: csharp
script:
  - ./build.sh BuildInstallFT