os:
  - osx
env:
  - GAUGE_HOME=./.gauge
before_install:
  - mozroots --import --sync
  - brew update; brew install Caskroom/cask/java
install:
  - brew outdated maven || brew upgrade maven
  - mvn -version
  - ./install_latest_gauge_nightly.sh
language: csharp
script:
  - ./build.sh BuildInstallFT