version: 1.0.{build}
init:
- ps: |
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    if (!(Test-Path -Path "C:\maven" )) {
    (new-object System.Net.WebClient).DownloadFile('http://www.us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip', 'C:\maven-bin.zip')
    [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
    }
- cmd: java -version
environment:
  GAUGE_PARALLEL: false
build_script:
- ps: >-
    .\install_latest_gauge_nightly.ps1

    $env:Path = "c:\Program Files\Gauge\bin;C:\maven\apache-maven-3.3.9\bin;" + [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

    Write-Host "PATH : $($env:PATH)"

    $env:M2_HOME=(where.exe mvn.cmd | Get-item).Directory.parent.FullName

    mvn --version

    .\build.cmd BuildInstallFT
test: off
artifacts:
- path: .\gauge-tests\reports-csharp\html-report
  name: html-report
on_finish:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path TestResults.xml))


    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\gauge-tests\reports-csharp\xml-report\result.xml))